// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: status.proto

package dk.via.JavaDAO.Status;

public final class Status {
  private Status() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Status_StatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Status_StatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Status_StatusMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Status_StatusMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014status.proto\022\006Status\"\017\n\rStatusRequest\"" +
      ">\n\rStatusMessage\022\016\n\006status\030\001 \001(\t\022\017\n\007mess" +
      "age\030\002 \001(\t\022\014\n\004data\030\003 \001(\t2R\n\rStatusService" +
      "\022A\n\017GetStatusMethod\022\025.Status.StatusReque" +
      "st\032\025.Status.StatusMessage\"\000B\031\n\025dk.via.Ja" +
      "vaDAO.StatusP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Status_StatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Status_StatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Status_StatusRequest_descriptor,
        new java.lang.String[] { });
    internal_static_Status_StatusMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Status_StatusMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Status_StatusMessage_descriptor,
        new java.lang.String[] { "Status", "Message", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
