// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: status.proto

package dk.via.JavaDAO.Status;

public interface StatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Status.StatusRequest)
    com.google.protobuf.MessageOrBuilder {
}
