on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'corretto'
#          cache: maven
      - name: Run the Maven verify phase
        run: mvn --batch-mode --update-snapshots verify
        working-directory: ./JavaDAO