on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'corretto'
          cache: maven
      - name: Build
        run: mvn --batch-mode -DskipTests package
        working-directory: ./JavaDAO
      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test 
        working-directory: ./JavaDAO